### ISSUE TITLE
Unclear error report

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/view3dscene#1]
See https://www.youtube.com/watch?v=rwut7_KCcJI at 6:38, the error occured at line 54, but view3dscene reported it at position (line?) 1137, make it hard to locate errors in large scene.

**Comment by michaliskambi** [comment]
The "position 1137" means that it's the 1137th character since the beginning of the file (counting newlines as 1 or 2 characters, depending whether the file uses Unix line endings or DOS/Windows line endings). It can be navigated to using Emacs "M-x goto-char ..." command. In Notepad++, it seems you can use Ctrl + G with "Offset" (http://superuser.com/questions/895025/how-to-know-cursor-position-index-in-an-editor ) or use this trick with selection: http://superuser.com/questions/895025/how-to-know-cursor-position-index-in-an-editor .

I know, it's not a proper solution, not every text editor has a feature "goto character position". We should just show the line and column number, like all normal programs:) I'll fix it in a couple of days.

**Comment by michaliskambi** [comment]
Fixed:) view3dscene (and all other programs using Castle Game Engine) will not show nice line/column numbers in the error messages, like

> view3dscene: VRML/X3D warning: Error when reading, will skip the rest of VRML/X3D file: Error at line 12 column 4:  ...

The fix is in castle-engine, https://github.com/castle-engine/castle-engine/commit/fd797c6abc2779859d190ab96746b769940038f9 , if you're interested:) The underlying stream wrapper keeps the count of current line and column now. The X3D lexer passes this information, in case of errors/warnings. There's a number of autotests to make sure it works correctly always:)

To test the result, you can get view3dscene from snapshots: http://michalis.ii.uni.wroc.pl/castle-engine-snapshots/

Or you can of course get Castle Game Engine and view3dscene from the latest GitHub sources, and compile them yourself:)
