### ISSUE TITLE
negative scale (reflected) geometry has incorrect lighting

### ISSUE THREAD

**Issue by splace** [castle-engine/view3dscene#12]
below code, (white box with reflected box next to it) produces this....

![box_0](https://user-images.githubusercontent.com/1234848/52313842-04021280-29a8-11e9-84a4-f5a58ea06bf8.png)

```
<?xml version="1.0" encoding="UTF-8"?>
<X3D profile="Interchange" version="3.0">
<head>
	<meta name="generator" content="view3dscene, http://castle-engine.sourceforge.net/view3dscene.php" />
</head>
<Scene>
	<Shape DEF="whitebox">
		<Appearance>
			<Material />
		</Appearance>
		<Box />
	</Shape>
	<Transform
		scale="-1 1 1"
		translation="2 0 0">
		<Shape USE="whitebox" />
	</Transform>
</Scene>
</X3D>
```

**Comment by michaliskambi** [comment]
Lighting is not supported on 3D objects with negative scale, I'm afraid. Negative scale changes the normal vectors, making the light calculation not doing what we would like to :)

I think that most 3D viewers (for X3D or not, including other game engines) will behave like this for objects with negative scale.

This is documented deep inside the engine, at TCastleTransform.Scale, https://castle-engine.io/apidoc-unstable/html/CastleTransform.TCastleTransform.html#Scale .

**Comment by splace** [comment]
thanks, this came up because i imported some nice Collada, that didn't look right, and found it had made extensive use of -ve scale. if this is common practice in Collada then a flip during import might be nice? unfortunately this will lose some of efficient geometry reuse, unless it is possible to just flip a IFS's winding (CCW/CW) to cure it?

**Comment by splace** [comment]
> just flip a IFS's winding (CCW/CW) to cure it?

i now see that unfortunately an IFS's coordIndex is not a node, so you cant re'USE the geometry with flipped winding! (without using a script)

**Comment by michaliskambi** [comment]
I don't think it's a common practice in Collada. Negative scale is a bad idea if you want to use lighting -- this is true regardless of the 3D format used to store the 3D data.

To fix this, one should "apply" the scale to the underlying coordinates, such that vertex positions are changed, and the resulting model may have "no scale" (i.e. scale="1 1 1"). (And reUSEing the Coordinate node between flipped and unflipped versions is no longer possible.)

But doing this automatically is not possible in a general case, since there may be a tree of transformations (`Transform` nodes in X3D), and negative scale may occur at any point. So this is something that needs to be fixed by the author of the 3D model. In Blender, you would use Ctrl + A (apply) and choose "Scale" to do this. But it only works on the given "Blender Object" transformation, it does not apply the possible scale defined at a parent, or parent of a parent etc.

Note that there is a `ccw` field at `IndexedFaceSet`, you don't need to process the `coordIndex` to flip the winding.

An alternative approach to normal calculation, that would always work, but costs time, is to calculate normals in the shader, using alread-transformed vertex coordinates or even `dFdx` and `dFdy` functions, like three.js does in various situations. See the `vec3 normal = normalize( cross( dFdx( vViewPosition ), dFdy( vViewPosition ) ) );`  mentioned on https://stackoverflow.com/questions/17528878/compute-normals-from-displacement-map-in-three-js-r-58 . An actual implementation seems to be in https://github.com/mrdoob/three.js/blob/2ad018c7c7ad103c9da9d7f22b3154537384ab26/src/renderers/shaders/ShaderChunk/normal_fragment_begin.glsl.js .
