### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by fwilamo** [castle-engine/view3dscene#14]
I am using version 3.18.0. If I am loading a obj file which comes with an mtl and jpg as texture, I get the following message.
![error](https://user-images.githubusercontent.com/20999927/59771253-a1037f00-92a9-11e9-8a90-05cee7c5c214.jpg)

The obj file has a size of 50MB, the texture file is 7MByte. Other tools manage to show the 3D model with texture information. Is there any way of getting more information about the problem?

**Comment by michaliskambi** [comment]
1. Our internal collision detection structures sometimes eat quite a lot of memory. Although it seems that texture loading makes the EOutOfMemory error, but maybe the collision data is already too large. Can you disable "Collisions" (click the appropriate button on the toolbar) *before* opening the model, and see if that helps?

2. Can you check the view3dscene version from snapshots, http://michalis.ii.uni.wroc.pl/view3dscene-snapshots/ ? This contains many improvements since the last release. If possible, please check it both with "Collisions" on and off.

3. If you use 32-bit version (i386), please check the 64-bit version (x86_64) if you have a 64-bit OS.

4. If you can attach the model and texture to reproduce the problem, please do. If you don't want to attach it publicly, but can send it to me in private (I hereby promise to use it only for the investigation of this bugreport, and never share it with anyone), then you can send it to `michalis.kambi@gmail.com`.

**Comment by fwilamo** [comment]
Yes. It works without the collision detection. I had to change the texture method after loading, but it works like expected now. Thanks a lot for your fast response. Happy to use it.
