### ISSUE TITLE
macOS 64 bit release

### ISSUE THREAD

**Issue by feliciabarbato** [castle-engine/view3dscene#22]
Hi i was using view3dscene. since i updated to mac os catalina i'm not able to run the app anymore. does it exists a 64 bit release for mac os?

is there any other free software able to view wrl files on mac os?

**Comment by michaliskambi** [comment]
Indeed, we don't yet have 64-bit release for macOS (as it requires changing the GUI library underneath). I will hopefully fix it sometime in next month (November).

**Comment by feliciabarbato** [comment]
ok!
thanks i’m lost without it

**Comment by michaliskambi** [comment]
Sorry for forgetting about this issue -- it is solved since a long time, I just forgot to update this ticket :) 

We did a lot of updates, also specific to macOS, since this ticket (see e.g. https://castle-engine.io/wp/2022/05/29/huge-improvements-for-macos-users-macos-binary-beta-release-cocoa-backend-for-tcastlewindow-automatic-running-and-packing-using-appbundle-access-to-macos-thanks-to-macstadium/ ) both to [view3dscene](https://castle-engine.io/view3dscene.php) and the underlying [Castle Game Engine](https://castle-engine.io/).

The view3dscene for 64-bit macOS is available from our usual page, https://castle-engine.io/view3dscene.php . I recommend to download now version "Download (Snapshot) Version 4.3.0:" , it is newer and close to our next 4.4.0 release. Anyway, whichever version you choose (4.2.0 or 4.3.0) from that page, it has a 64-bit macOS support :)
