### ISSUE TITLE
Default Viewpoint at 0,0,0

### ISSUE THREAD

**Issue by andreasplesch** [castle-engine/view3dscene#3]
In X3D scenes without an explicit viewpoint node, the initial camera position is at 0,0,0. However, the default X3D viewpoint position is at 0,0,10.
It is easy to use the menu to navigate to the default X3D viewpoint but it took me a while to realize that there was not any problem with a scene itself, just the ciew3dscene initial camera position.
Here is an example:
http://x3dom-integertrigger.glitch.me/IntegerTrigger_test.x3d

**Comment by michaliskambi** [comment]
Thanks for reporting! In short: fixed.

The view3dscene binary that includes the fix will be available on http://michalis.ii.uni.wroc.pl/castle-engine-snapshots/ in ~15 minutes, so you can test it immediately :)

Longer explanation:

Part of this is a feature, not a bug :)

When the X3D scene does not contain any Viewpoint, the view3dscene deliberately does _not_ use the default X3D viewpoint at 0,0,10. Instead, it calculates a suitable viewpoint to see the whole model, looking at the bounding box of the model, so it should be nice for both very small and very large models. Such automatic calculation shows a good view for models on which the author did not specify a suitable viewpoint, which is useful --- I often use view3dscene to browse "3D assets": things like buildings or creatures, that are not meant to be a "complete 3D world", and so they often don't include a sensible viewpoint to see the whole model.

You can test this auto-calculated viewpoint explicitly, on any scene, using _"Navigation -> Jump To Viewpoint -> Calculated viewpoint to see the scene (+Y up, -Z dir)"_.

The idea is that if an author wants to have a default viewpoint, then it's easy to add a `<Viewpoint />` to the X3D scene, to disable this automatic calculation.

Now, there was still a bug: this automatic calculation was supposed to show a _better_ view than the default 0,0,10, but in this case it failed, the view with 0,0,0 position was not useful. The reason is that the initial bounding box of your scene is empty (`Switcher.whichChoice` is -1 initially) and in this case current code was using 0,0,0 position instead of 0,0,10 -- this is fixed now :)

**Comment by andreasplesch** [comment]
ok. I can confirm that the latest nightly has the fix. While most browser would use a default viewpoint if none is given, I agree that determining a best viewpoint is very sensible and probably spec. conforming. A 'see all' option is often needed and perhaps worth a keyboard shortcut: CTRL-A ? X3DOM uses 'a'.
