### ISSUE TITLE
View3dScene isn't network enabled

### ISSUE THREAD

**Issue by peardox** [castle-engine/view3dscene#33]
OK - maybe I'm expecting too much :)

I just threw together a test for the new and really useful TextureNode.LoadFromImage(TextureImage, TakeOwnership, ImageURL);

I noticed I can set the URL to wherever I want so I set it to the real URL (even though testing with a local copy) and used the new SaveNode method to write out the x3dv

Loading the x3dv back into view3dscene raises the following warnings...

The 'back.jpg' I can actually correct for now (static, local) but the internetified image (its real) needs TDownload enabling

```
2 warnings:

Texture: Cannot load the texture:
  Error EDownloadError when loading texture from URL "https://c1.scryfall.com/file/scryfall-cards/large/front/1/6/161d1277-05e8-4503-a3a5-4d47309abdd0.jpg?1600982001;": Downloading network resources (from "http" or "https" protocols) is not enabled
Texture: Cannot load the texture:
  Error EDownloadError when loading texture from URL "castle-data:/back.png": Error when downloading "castle-data:/back.png": Exception "EFOpenError":
Unable to open file "C:\dev\view3dscene\back.png": The system cannot find the file specified.

Scene URL: "C:\dev\play\ArtCards\data\scene.x3dv".
Use "File->View Warnings" menu to view these warnings again.

```

**Comment by michaliskambi** [comment]
Enable them by _"Preferences -> Download Resources From Network"_. They are disabled by default, because the textures/Inlines/audio is downloaded in synchronous mode for now (so it blocks view3dscene without even a button to "cancel").

It is mentioned in the dialog box on Ctrl + L, although I see in your case you miss it as you open a local file (but with links to http/https).
