### ISSUE TITLE
ecmascript:  protocol not recognized

### ISSUE THREAD

**Issue by andreasplesch** [castle-engine/view3dscene#4]
Script nodes can have inlined code using a special ecmascript protocol. Here is an example:

http://www.web3d.org/x3d/content/examples/ConformanceNist/Miscellaneous/Script/ScriptNodeEventOutControl_EcmaScriptIndex.html

The x3d:
http://www.web3d.org/x3d/content/examples/ConformanceNist/Miscellaneous/Script/ScriptNodeEventOutControl_EcmaScript.x3d

There is an error that no supported protocol is found and script is ignored,

This is especially useful for protos in order to keep everything in a single file.

**Comment by michaliskambi** [comment]
I'm afraid we do not support ECMAScript / JavaScript right now in view3dscene and Castle Game Engine, at all (inlined or not inlined). We plan to support it (see https://castle-engine.sourceforge.io/planned_features.php , most probably using https://github.com/bero1985/besen ), but there wasn't time to do it yet.

I know it is a large missing feature for an X3D browser, like view3dscene. But it turned out that Castle Game Engine doesn't need scripting (through the X3D Script node) much. Game logic in CGE is in 95% cases comfortably coded using Pascal code that treats X3D scenes as assets (with animations and sensors inside, but no need for embedded scripts). That's why it's not implemented yet -- the priority of this feature was not high enough, yet.

For now, inside X3D Script node you can use our custom scripting language CastleScript ( https://castle-engine.sourceforge.io/castle_script.php ) or use a special "compiled" protocol that connect Script node with compiled Pascal methods (see https://castle-engine.sourceforge.io/x3d_extensions.php#section_ext_script_compiled ).

I'm labeling this issue "enhancement" -- the ecmascript integration *will* happen, but I'm afraid not in the immediate release.

**Comment by andreasplesch** [comment]
No worries. Given that almost everything else is supported very well, I had just assumed that ecmascripting is as well.

It should be pretty straightforward to convert the script for my ScalarSequencer to castlescript probably looking a bit strange then.

I noticed in the castlescript examples that the set_ and _change convention is not used. I am curious what the reason could be ?

**Comment by andreasplesch** [comment]
I tried to rewrite the script as castlescript:

https://glitch.com/edit/#!/ripe-taxi?path=ScalarSequencerCastle.x3d:19:10

http://ripe-taxi.glitch.me/ScalarSequencerCastle.x3d

I get now a 414 unexpected response error and no supported protocol found.

Loading from a local file produces a Exception EFOpen error.

https://www.freepascal.org/docs-html/rtl/classes/efopenerror.html

not sure what else to try. Is there a .x3d example with castlescript ?

**Comment by andreasplesch** [comment]
ok, I figured out the white space in front of the castlescript: identifier caused the problem.

http://ripe-taxi.glitch.me/ScalarSequencerCastle.x3d

now does not have warnings anymore but does not work, even the non-script/proto parts.
Investigating.

**Comment by andreasplesch** [comment]
http://ripe-taxi.glitch.me/push4button.x3d

is the scene without the script.

It works as intended in x_ite and Instant Player. freeWrl and BSContact do button animation but not the text switching, perhaps due to lack of event utility support. view3dscene has no warnings but does not do the button animation nor the text switching. 

I see if I can narrow this down and perhaps then submit a new issue.

**Comment by andreasplesch** [comment]
Cool the ScalarSequencer proto works now:

http://ripe-taxi.glitch.me/ScalarSequencerCastle.x3d

The TimeSensor had a stopTime=1 which confused castleengine. Probably a spec. detail issue.

castlescript is fine but no early return from functions, or breaking out of loops takes a little adjusting. Also easy to forget that there is no semicolon after the last statement of a block. Ecmascript would be quite powerful but probably not necessary if the scene is mostly controlled from the outside (Pascal). Although Protos then could become a better encapsulation method.

Anyways, closing.

**Comment by michaliskambi** [comment]
Cool, I see that everything is resolved :) Thank you!

As for the CastleScript lacks (no early return, strict semicolon treatment): the CastleScript language has indeed many problems making it uncomfortable for non-trivial scripts. Instead of fixing them, I decided that it's better to implement ECMAScript support... I still didn't find time for ECMAScript, but I feel that it's more optimal to put work into ECMAScript than into improving a CastleScript language.

If you can reproduce the TimeSensor bug/inconsistency, can you please report it as a separate issue? The engine should have TimeSensor treatment that 100% conforms to the X3D specification.

**Comment by andreasplesch** [comment]
Hm, I restored stopTime='1' to http://ripe-taxi.glitch.me/ScalarSequencerCastle.x3d and it does work. Not sure what happened. I think there is some caching if the url/file shortcuts are used ? But it looks like false alarm.
BESEN looks like it is well tested but does not currently have a lot of activity. Ecmascript5 would suffice for practically any purposes.

**Comment by michaliskambi** [comment]
There is caching of various resources (textures, models), but it's based only on reference counts (for now). And for X3D models, it's used only when multiple EXTERNPROTO refer to the same model. IOW, it should not affect you if you simply reopen the model in view3dscene. Thank you for testing, let me know if you encounter this again!
