### ISSUE TITLE
tovrmlx3d hangs on conversion

### ISSUE THREAD

**Issue by davidhedley** [castle-engine/view3dscene#43]
I have a VRML 2.0 file created by a third party that I am trying to convert to X3D. When using tovrmlx3d it prints a load of warnings such as:
`tovrmlx3d: Warning: VRML/X3D: Cycles in VRML/X3D graph: USE clause inside node "Caution_1_d31" refers to the same node`
but then seems to just hang and never completes. I have tried v4.0.0 and v4.1.0. 

Can anyone offer any guidance?

**Comment by michaliskambi** [comment]
I received the model in private and the main fix is https://github.com/castle-engine/castle-engine/commit/57aa7c6cdf670ece23306512d7c37cefb3464045 . The conversion didn't really hang, but took a reaaaally long time due to unoptimal `RenameUniquelyCore`. This is fixed, it is now ~instant.

On top of it, I also dealt with (some) cases of `VRML/X3D: Cycles in VRML/X3D graph: USE clause inside node ...` warning. When they happen because of "interface declaration" in VRML/X3D (which is when e.g. `Script` is used) -- the cycle in VRML/X3D is actually accepted now and handled OK.
