### ISSUE TITLE
white space in front of castlescript: identifier

### ISSUE THREAD

**Issue by andreasplesch** [castle-engine/view3dscene#5]
In x3d encoding, leading white space in front of the castlescript: identifier in the value for the url field of a script node provokes a parsing error.

Perhaps this is intended but probably not. Could provide an example by converting the ballgame example to x3d and adding a space.

**Comment by michaliskambi** [comment]
Fixed in https://github.com/castle-engine/castle-engine/commit/65d55fb7074822670e0ff31ddad21c9c7c961ae3 , thank you for reporting! And added to automatic tests, so it doesn't happen again.

( One function tolerated whitespace before protocol (like "castlescript:"), but another function earlier was trying to make the URL absolute and didn't account for this whitespace. )

A new view3dscene version will be automatically build in ~15 minutes on http://michalis.ii.uni.wroc.pl/castle-engine-snapshots/ .

**Comment by andreasplesch** [comment]
Trying the snapshot from around 7EST, I get protocol warnings with
 
http://ripe-taxi.glitch.me/spacecastle_test.x3d

 ?

**Comment by michaliskambi** [comment]
I forgot that these snapshots are regenerated daily, *not* automatically after every repository change, because of.. well, historic reasons.

I clicked the snapshots to regenerate now, and I reconfigured the Jenkins job to happen automatically after every CGE or view3dscene repo change. Thanks for noticing this.

**Comment by andreasplesch** [comment]
ok. I am using Windows at home, and 64 bit Linux in the office, so will test later.

**Comment by michaliskambi** [comment]
( I have it on my TODO list to switch generating snapshots for Linux to 64-bit (x68_64). For now, Jenkins system is an old 32-bit Linux, so it was easier to set up compiling snapshots for 32-bit Linux. I know that 64-bit is more popular nowadays :)

**Comment by andreasplesch** [comment]
Since the repos are on github anyways you could look into travis-ci ?  It would be a bit of setup but perhaps not too bad.

**Comment by andreasplesch** [comment]
snapshot works fine with http://ripe-taxi.glitch.me/spacecastle_test.x3d here as well. Thanks!
