### ISSUE TITLE
TwoSidedMaterial, backColor

### ISSUE THREAD

**Issue by brutzman** [castle-engine/view3dscene#74]
Here is a test scene for TwoSidedMaterial

- https://www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter05AppearanceMaterialTextures/TwoSidedMaterialExampleIndex.html
- https://www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter05AppearanceMaterialTextures/TwoSidedMaterialExample.x3d
- https://www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter05AppearanceMaterialTextures/TwoSidedMaterialExample.x3dv

view3dscene reports:
```
1 warnings:
TwoSidedMaterial X3D node (TwoSidedMaterial) with SeparateBackColor = true is not supported yet
```

tovrmlx3d.exe reports:
```
ClassicVRML validation: tovrmlx3d.exe Chapter05AppearanceMaterialTextures//TwoSidedMaterialExample.x3dv --validate --enable-downloads
tovrmlx3d: Warning: VRML/X3D: Error when reading, will skip the rest of X3D file: Error at line 56 column 25: Invalid X3D node content (probably unknown or not allowed field, prototype or VRML 1.0-style children) inside "Appearance": got "TwoSidedMaterial"
Exception "Exception":
```

**Comment by michaliskambi** [comment]
1\. The "Classic VRML" (.x3dv, https://www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter05AppearanceMaterialTextures/TwoSidedMaterialExample.x3dv ) version has an error, i.e. it is indeed invalid file, from what I can see.

Both tovrmlx3d and view3dscene report it correctly.

```
VRML/X3D: Error when reading, will skip the rest of X3D file: Error at line 56 column 25: Invalid X3D node content (probably unknown or not allowed field, prototype or VRML 1.0-style children) inside "Appearance": got "TwoSidedMaterial"
```

That's indeed an error in file (maybe error at conversion XML->classic?). File contains

```
      appearance Appearance {
        TwoSidedMaterial {
```

but it should be 

```
      appearance Appearance {
        material TwoSidedMaterial {
```

(i.e. the file misses "material" field name, obligatory at this place in classic encoding.)

2\. In XML encoding, the file is correct wrt to the specification. The warning

```
TwoSidedMaterial X3D node (TwoSidedMaterial) with SeparateBackColor = true is not supported yet
```

is actually about our implementation. Still I'm keen to keep this warning -- esp. since TwoSidedMaterial is deprecated, and it has no equivalent in other 3D formats (like glTF), the `SeparateBackColor = true` case is unlikely to be ever implemented in CGE/view3dscene.

Hm, I understand this may be undesirable to you if you use CGE/view3dscene for validation: since this is reported as validation error, but actually the X3D XML version is valid. I'm not yet sure how to proceed --

A. if one looks at `tovrmlx3d --validate ...` as only a tool for validation wrt to the X3D spec, then indeed this is invalid warning. OTOH, 

B. if one looks at `tovrmlx3d --validate ...` as a tool to judge whether this is sensible in CGE/view3dscene, or in future X3D, then the warning makes sense.

I guess A makes more sense. `tovrmlx3d --validate ...` should not report things that are valid X3D, but discouraged (and/or not implemented fully) for some reason in CGE/view3dscene. It should only report things that are indeed errors with respect to the spec.

I'm leaving this open to solve AD 2.

**Comment by brutzman** [comment]
Thanks for diagnosis I should have caught that. I've fixed the stylesheet error producing TwoSidedMaterialExample.x3dv

I agree with option B and similarly prefer getting warnings whenever they exist.  (The worst problems are the ones you don't know exist.)

TwoSidedMaterial is definitely a useful node for X3D authors.  Hoping that someday it might be possible to devise a repeatable pattern for mapping it from X3D to glTF, it that can be straightforward then we don't need to remove it someday.

**Comment by michaliskambi** [comment]
> I agree with option B and similarly prefer getting warnings whenever they exist. (The worst problems are the ones you don't know exist.)

Thanks. OK, so in this case -> nothing to be done here on my side :) 

> TwoSidedMaterial is definitely a useful node for X3D authors. Hoping that someday it might be possible to devise a repeatable pattern for mapping it from X3D to glTF, it that can be straightforward then we don't need to remove it someday.

There is a pattern to translate:

- `TwoSidedMaterial` with `separateBackColor = false` is useless, as we concluded on one x3d-public thread. One can then just use `Material` and make `solid=false`. No point in using `TwoSidedMaterial`.
- `TwoSidedMaterial` with `separateBackColor = true` can be converted into 2 shapes, both using the same coordinates, both with `solid=true`, one with `ccw=false`, one with `ccw=true`. That's practically how (everyone except X3D?) is realizing the same goal (display a mesh that has different colors from each side). Browsers can make rendering of this efficient. And this way, browsers don't need to implement special shader only for the case of `TwoSidedMaterial` with `separateBackColor = true` (which is very  rare case in practice, in my experience -- likely because other tools also don't support it, e.g. you cannot author such materials in Blender anyway).

**Comment by brutzman** [comment]
Thanks for helpful pattern.  Looking ahead: am expecting that we will list this pattern, and perhaps others, as part of a future X3D Recommended Practices for glTF.  Working to consensus that such correspondences are possible for TwoSidedMaterial will let us remove the deprecation in X3D 4.1 someday.  This is healthy progress.

Historical precedent: our only other deprecation in X3D was later rescinded.  The GeoOrigin node was deprecated when implementations found it unnecessary due to newer preprocessing algorithms.  Several years later it was found to have unavoidable merit, and deprecation rescinded, when GeoOrigin was found to be necessary for proper geospatial implementations on mobile phones and computers with limited processing power.  Careful evolution is really valuable.
