### ISSUE TITLE
permit '\n' and other special characters in JavaScript source

### ISSUE THREAD

**Issue by brutzman** [castle-engine/view3dscene#75]
Numerous models in X3D example archives include '\n' characters in script source code.  Test file:

- https://www.web3d.org/x3d/content/examples/X3dForAdvancedModeling/Animation/ViewpointSequencerPrototype.x3d
- https://www.web3d.org/x3d/content/examples/X3dForAdvancedModeling/Animation/ViewpointSequencerPrototype.x3dv
- https://www.web3d.org/x3d/content/examples/X3dForAdvancedModeling/Animation/ViewpointSequencerPrototypeIndex.html

Build logs available at
- https://sourceforge.net/p/x3d/code/HEAD/tree/www.web3d.org/x3d/content/examples/build.x3dv.all.log.txt

tovrmlx3d.exe reports:
```
C:\x3d-code\www.web3d.org\x3d\content\examples\X3dForAdvancedModeling/Animation//ViewpointSequencerPrototype.x3d processing with X3dToX3dvClassicVrmlEncoding stylesheet
ClassicVRML validation: tovrmlx3d.exe Animation//ViewpointSequencerPrototype.x3dv --validate --enable-downloads
tovrmlx3d: Warning: X3D: Invalid X3D file: Invalid sequence in a string: "\n". Backslash must be followed by another backslash or double quote, for SFString and MFString (in X3D classic (VRML) encoding) and for MFString (in X3D XML encoding).
tovrmlx3d: Warning: X3D: Invalid X3D file: Invalid sequence in a string: "\n". Backslash must be followed by another backslash or double quote, for SFString and MFString (in X3D classic (VRML) encoding) and for MFString (in X3D XML encoding).
Exception "Exception":
Validation failed (consult the warnings above), exiting with non-zero status
Result: 1
```

Offending javascript:
```
function tracePrint(outputString)
{
	if (traceEnabled) Browser.print ('[ViewpointSequencer] ' + outputString + '\n');
}
```

The above problem could be avoided by using _Browser.println()_ instead, but historically not all X3D browsers supported that function.

In any case this seems like a good general problem to address.

- The X3D Architecture and ClassicVRML encoding grammar do no distinguish between the three common uses of MFString: displayable text, url, or source code.
- We do not ever want to obfuscate source code for a given encoding, if it can possibly be avoided, since that leads to untold problems and essentially breaks interoperability.

Of note is that the ECMAScript specification specifically allows '\n' and other related special characters.

- ECMA-262, 14th edition, June 2023, ECMAScript® 2023 Language Specification
- Table 37: String Single Character Escape Sequences
- https://262.ecma-international.org/14.0/#table-string-single-character-escape-sequences

![image](https://github.com/castle-engine/view3dscene/assets/7712992/62620406-abdc-4455-bb3a-e852e6b2e020)

Recommendation: permit such backslash-escaped single-character definitions in contained source code.

Consideration: this is pretty involved... it might be useful to discuss on x3d-public list.  If further X3D specification changes seem to be needed, we can likely apply them in the upcoming revision to the ClassicVRML encoding as part of string rules and grammar.

**Comment by michaliskambi** [comment]
Backslashes are necessary when encoding strings (whatever their content) in X3D and VRML. This affects both SFString and MFString in classic encoding, and MFString in X3D XML encoding. We did talk about it on x3d-public. See https://github.com/michaliskambi/x3d-tests/wiki/Clarify-the-usage-of-quotes-and-backslashes-for-MFString-and-SFString-in-XML-encoding which includes tests on other browsers.

Specifications of string encoding indeed does not distinguish whether string contains a JavaScript source code or something else -- and it shouldn't have, in my opinion, it would be quite confusing if we had different rules depending on usage. At the parsing level, you are parsing a string, and the intent of this string is not relevant. The need to use backslashes comes from the same reason, and so remains sensible whatever the string contents are (JavaScript or not).
 
We cannot "just allow `\n`" because this has consequences causing unambuiguity. We use backslashes to make sure double quotes are understood correctly (when do they terminate string and when they are part of string contents). Consequently, we need to use something special to express backslash itself, we do this be repeating the double quote. This is similar to decision in similar programming languages.

So, in this case I think CGE/view3dscene follow the spec, and the spec is good, we *should not* change it. It would create unambiguous cases that cause additional confusion, like `Text { string "\\n" }` or `Text { string "\"\\n" }` or `Text { string "\\\n" }`. 

If need be, we can continue to talk on x3d-public. Though I have to say my mind is a bit set about this, and the encoding of strings was also discussed many times on x3d-public :)

**Comment by brutzman** [comment]
Sorry but we cannot accept non-interoperable javascript source between encodings.  That path leads to broken content.

So please leave this issue open, and we will work through potential approaches on the list after Web3D 2023.

**Comment by michaliskambi** [comment]
> Sorry but we cannot accept non-interoperable javascript source between encodings. That path leads to broken content.

I don't get this statement, sorry. Naturally you can express any JavaScript, in any encoding, and you can convert reliably between encodings, it all works. As I mentioned above, backslashes also apply to MFString in X3D XML, as we concluded long time ago on x3d-public.

CGE/view3dscene here follow the spec, and follow what others are doing, as far as I know, as we also talked and tested during https://github.com/michaliskambi/x3d-tests/wiki/Clarify-the-usage-of-quotes-and-backslashes-for-MFString-and-SFString-in-XML-encoding . 

My point is just: whatever you write in a string, whether it's JavaScript or not, you then encode it in X3D (classic or XML) using their rules for string encoding. 

- In classic (for SFString and MFString) you have to use `\"` to express double qoute inside a string, and `\\` to express a single backslash. Consequently, `\n` is an error -- if you want to express `\n` in JavaScript, then X3D should have doubled backslashes,

     `Script { url { "javascript: foo(\"one line\\nsecond line\");" } }`

    and for JavaScript parser it sees then

    `foo("one line\nsecond line");`

- In XML (for MFString) this is also the case, see above.

**Comment by brutzman** [comment]
I understand the point... am referring to large text blocks of code.  Authors need to be able to copy them without obfuscation or recovery.  Example of unmodified ecmascript: source code appearing identically in different X3D file encodings:

- https://www.web3d.org/x3d/content/examples/Vrml2Sourcebook/Chapter30Scripts/Figure30_1ScriptSlidingBallIndex.html

- https://www.web3d.org/x3d/content/examples/Vrml2Sourcebook/Chapter30Scripts/Figure30_1ScriptSlidingBall.x3d
```
      <!-- Third Script example, using preferred method: script code contained in CDATA block -->
      <Script DEF='MoverUsingContainedScript'>
        <field accessType='inputOnly' appinfo='receive fraction from clock' name='set_fraction' type='SFFloat'/>
        <field accessType='outputOnly' appinfo='produce output position to move the ball' name='value_changed' type='SFVec3f'/>
        <![CDATA[
ecmascript:

// Move a shape in a straight path
function set_fraction( fraction, eventTime ) {
	value_changed[0] = fraction;  // X component
	value_changed[1] = 0.0;         // Y component
	value_changed[2] = 0.0;         // Z component
}
]]>
      </Script>
```

- https://www.web3d.org/x3d/content/examples/Vrml2Sourcebook/Chapter30Scripts/Figure30_1ScriptSlidingBall.x3dv

```
      # Third Script example, using preferred method: script code contained in CDATA block
      DEF MoverUsingContainedScript Script {
        inputOnly      SFFloat	set_fraction          # [appinfo] receive fraction from clock
        outputOnly     SFVec3f	value_changed     # [appinfo] produce output position to move the ball
	url [ "ecmascript:

// Move a shape in a straight path
function set_fraction( fraction, eventTime ) {
	value_changed[0] = fraction;    // X component
	value_changed[1] = 0.0;         // Y component
	value_changed[2] = 0.0;         // Z component
}
" ]
      }
```

- Successful X3dToClassicVRML.xslt conversion and tovrmlx3d.exe validation from build.x3dv.all.log.txt:

```
C:\x3d-code\www.web3d.org\x3d\content\examples\Vrml2Sourcebook/Chapter30Scripts//Figure30_1ScriptSlidingBall.x3d processing with X3dToX3dvClassicVrmlEncoding stylesheet
ClassicVRML validation: tovrmlx3d.exe Chapter30Scripts//Figure30_1ScriptSlidingBall.x3dv --validate --enable-downloads
```

**Comment by brutzman** [comment]
One other helpful reaction that Dick Puk made, when reviewing this during last Friday's X3D Working Group meeting:  character entities that use multiple characters, to define a single character, can indeed be considered a single character.  Example:

- _**\n**_ is a single newline character,
- _**\\n**_ defines two individual text characters, "\" and "n"

"Letting ECMAScript be ECMAScript" without modification thus appears to be possible, if we are careful about all this.

**Comment by michaliskambi** [comment]
> I understand the point... am referring to large text blocks of code. Authors need to be able to copy them without obfuscation or recovery.

The way strings work in X3D means you need to use backslashes to secure double quotes.

That's also how it works in C, C#, EmacsLisp and similar languages that have similar syntax for strings.  If you want to put something inside a string -- sorry, but you need to make sure to deal with double quotes and backslashes, it is not "mindless copy-paste".

And it cannot be "mindless copy-paste" because you need some way to "protect" double quotes, and this means that backslashes become special.

> One other helpful reaction that Dick Puk made, when reviewing this during last Friday's X3D Working Group meeting: character entities that use multiple characters, to define a single character, can indeed be considered a single character. Example:
>    "\n" in a string defines a single newline character,
>    "\\n" in a string defines two individual text characters, "\" and "n"

- `\n`, when seen by JavaScript parser, indeed results in placing a single character (well, at least on Unix): ASCII code 10, Unix newline.
- The source code of JavaScript expressed it by 2 characters, backslash and n.
- But you need to be aware that when you write X3D, the X3D parser sees it first. X3D parser must be able to make sense of where the string literal ends, and how many backslashes and double quotes it contains within its content. 
- The source code of X3D says that to express a backslash, you need to write 2 backslashes.

It is the same as in EmacsLisp. I want to write a regular expression matching "\n". Well, then I write `\\n`, because backslash is special in EmacsLisp string literals.

For me, X3D is really the same as C, C#, EmacsLisp. And that's good. And it doesn't matter if string represents JavaScript or any other content, which should not be relevant during parsing, this is also good.

Your examples given above don't really relate to the issue, you don't have there double quotes or backslashes in JS content, moreover one uses CDATA in XML which is kind of special.

**Comment by brutzman** [comment]
Again thanks for your thoughts.  Am not asking to ignore the rules, rather trying to be super precise.  Am focused on results and how we can get there all together, validly and repeatably and unambiguously.

It seems pretty clear that _single-backslash-n_ is one character and _double-backslash-n_ is two characters, in each of these X3D encodings and in ECMAScript standard as well. 

The consistent embedded _ecmascript:_ source appearing in XML and ClassicVRML encodings, provided in the Figure30_1ScriptSlidingBall example above, shows that such consistency is indeed possible.  Getting to clarity on handling of special characters (whether individual or multiple characters) is always good for any set of encoding rules.

**Comment by michaliskambi** [comment]
> It seems pretty clear that single-backslash-n is one character and double-backslash-n is two characters, in each of these X3D encodings and in ECMAScript standard as well.

That's a bit ambiguous statement for me. Let me phrase what I'm saying in a way that is clear:

- In X3D classic encoding of MFString and SFString, and in X3D XML encoding of MFString, you need to use three characters: `\\n` . Backslash + backslash + n.
- This means that JavaScript parser sees 2 characters, `\n`, backslash + n.
- This means that the string contents, in JavaScript interpreter, contains a single character, which is a Unix newline (char 10).

> The consistent embedded ecmascript: source appearing in XML and ClassicVRML encodings, provided in the [Figure30_1ScriptSlidingBall](https://www.web3d.org/x3d/content/examples/Vrml2Sourcebook/Chapter30Scripts/Figure30_1ScriptSlidingBallIndex.html) example above, shows that such consistency is indeed possible.

Note that examples you show below that paragraph don't actually show the case we're discussing. The `set_fraction` you show each time doesn't do the thing that is interesting in this thread -- it doesn't contain any double quote or backslash inside the content. There's no problem in that case, indeed the code inside X3D string can be "mindlessly" copied and it is also a JavaScript code.

We are talking what happens if a script wants to express something that is a double quote, or backslash, for JavaScript parser.

I am saying that if you want JavaScript parser to see

```
foo("one line\nsecond line");
```

then in X3D classic encoding you need to use additional backslashes, so that it looks like this:

```
Script {
  url "ecmascript: foo(\"one line\\nsecond line\");"
}
```

(note the addition of 3 backslashes above -- to "protect" two double quotes and 1 backslash). And I'm saying it is good, X3D is consistent with how you would pass this string in C-like languages, for all the same reasons. Let's assume this example is Java. You would have to do something like this:

```
new Script("MoverUsingContainedScript").setSourceCode("\"one line\\nsecond line\"");
```

Java, for the exact same reason as X3D encodings, requires extra backslashes in the string literals. This makes sense, Java parser (just like X3D parser) must know where does the string end.

**Comment by brutzman** [comment]
n.b. I added further language representations in the preceding post.

Summary of _Script_ node _ecmascript:_ source representations:

1. **XML**.  Provided as contained string literals, protected from further escaping as CDATA (character data) block.
2. **HTML**. Can directly included XML-encoded X3D source (including Script nodes) within an HTML page.
3. **ClassicVRML**.  Provided in url field as one SFString in an MFString array, must start with _ecmascript:_ keyword.
4. **Java, Python, Turtle**.  Provided as contained string literals found within triple-apostrophe ''' delimiters.

Seems unlikely that any changes will be needed to X3D Abstract Architecture, which seems to be fully expressive for the seven unique representations above.  Of note is that the official ISO 19775-1 X3D 4.0 Architecture is unlikely to change for several years while X3D 4.1 evolves.

For SFString entries beginning with _ecmascript:_ header in _url_ fields, then our current options for ClassicVRML specification seem to be:
- accept special characters according to Table 37 above, or
- declare they are erroneous, in which case browser response is undefined (and can permissibly include acceptance).

If the X3D 19776-2 ClassicVRML Encoding needs further definitional prose or grammar rules to unambiguously handle these escape sequences, then great, let's do that.

**Comment by brutzman** [comment]
Further discussions this week confirmed that this is an open issue and the X3D Working Group will be working to formalize the requirement for consistent handling of ECMAScript source across each file encoding and programming language binding.

Of additional note is that ECMA standards for ECMAScript each get ratified by ISO/IEC as well.  So in addition to supporting portable correct source code, this consistent handling is necessary for required compatibility among multiple ISO standards as well.

Issue #79 describes the Web3D Consortium standards-development process on another necessary improvement.

Here is a better example scene, with source-code excerpt showing important author value when using `\n` newline characters.

- X3D Example Archives: Basic, course, Create X3D From String Random Spheres
- https://www.web3d.org/x3d/content/examples/Basic/course/CreateX3DFromStringRandomSpheresIndex.html

```
function initialize()
{
  for (i=0; i < 10; i++)
  {
    rand1 = 100*R();
    rand2 = 100*R();
    rand3 = 20*R();
    rand4 = 40*R();
    rand5 = 20*R();
    sceneString =    '<X3D version="3.1" profile="Interchange">\n' +
                     '  <Scene>\n' +
                     '      <Transform translation="' + rand1 + ' 0 ' + rand2 + '" >\n' +
                     '           <Shape>\n' +
                     '                   <Appearance>\n' +
                     '                      <Material diffuseColor="' + R() + ' ' + R() + ' ' + R() + '"/>\n' +
                     '                   </Appearance>\n' +
                     '                   <Sphere radius="' + (rand3 / 2) + '"/>\n' +
                     '           </Shape>\n' +
                     '      </Transform>\n' +
                     '  </Scene>\n' +
                     '</X3D>\n' +
                     '<!--==============================================-->\n';

       Browser.println (sceneString);
//     newNode = Browser.createVrmlFromString(sceneString);
       newNode = Browser.createX3DFromString(sceneString);
       ModifiableExternalNode.children[i] = newNode[0];
  }
}
```

**Comment by michaliskambi** [comment]
If you plan to change the spec, please let's get consensus about this on x3d-public. 

The current spec rule in unambiguous, implementable, allows for reliable conversion between any encoding, consistent with other C-like languages.

I don't have confidence that a change you propose will be unambiguous. There's a risk we'll land in some uncertain spec text that makes people confused even more about how to write MFString in X3D. 

For me, introducing a special rule for parsing when string starts with `ecmascript:` goes really against any language design. Noone else is doing something like this. I cited above Java and C-like languages, that behave just like X3D (right now): backslashes are used for quoting, if you want to write literal backslash than write it twice in source.

**Comment by brutzman** [comment]
X3D 4.0 Architecture is the governing specification and other specifications like ISO/IEC 19776-2 ClassicVrml Encoding will be upgraded to match. As ever we use Web3D Consortium process to achieve consensus in X3D Working Group on x3d-public@web3d.org mailing list. Your inputs remain vital. Thanks for all efforts.

**Comment by brutzman** [comment]
The upcoming ClassicVRML Encoding 4.0 specification will be changed to match the X3D 4.0 Architecture and the official ECMAScript specification, so consensus is already achieved. This issue is mistakenly closed.

**Comment by michaliskambi** [comment]
Please reopen this issue when the updated classic 4.0 specification will be available for public review.

I cannot reopen this now -- I wouldn't be able to do anything with it, as I don't have access to classic 4.0 specification, it is not public on https://www.web3d.org/standards , and I don't have access to Mantis anymore ( all links, like https://www.web3d.org/member-only/mantis/view.php?id=1444 , after logging-in redirect me to my Web3d membership page which just says "Community Membership" ).

And I'm really unclear what exactly specification change you did. As I mentioned above, 

- This is not only about classic encoding (or at least it should not be -- as both classic and XML encodings share the same rules for backslashes in MFString handling; here I talk about MFString in X3D XML attributes, not CDATA; unless you decided to break this consistency). 

- I don't see how you could define it in a way that would be consistent with what other C-like languages are doing with string literals.

- I don't see how you could define it in a way that doesn't break compatibility.

But I don't want to speculate too much or criticize something I don't know. So please let me know when this change is actually available for public review, and then reopen this and let's talk how/if I can address it in CGE/view3dscene.
