### ISSUE TITLE
RFE (Request for Enhancement)  Vertex shaders for Spheres

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/view3dscene#87]
Vertex shaders for spheres are pretty critical for my projects, unless PBR can do this:

https://coderextreme.net/X3DJSONLD/src/main/personal/cgeball.x3d

I'm trying to learn how to compile shaders, etc.  I'm not sure if that's necessary.

**Comment by coderextreme** [comment]
This is higher priority:

https://github.com/castle-engine/view3dscene/issues/39

Thanks!

**Comment by coderextreme** [comment]
Perhaps I just need to learn how to compile shaders.  I'm not sure how to read the first error message of https://coderextreme.net/X3DJSONLD/src/main/personal/cgeball.x3d I don't know if Spheres can't have vertex shaders, or the shader can't compile.

**Comment by coderextreme** [comment]
I finally found this, looking at it:

https://castle-engine.io/apidoc/html/CastleGLShaders.html

**Comment by coderextreme** [comment]
If you're wondering what's wrong with what's displayed,  I'm pretty sure the ball is supposed to be translucent and reflective, not magenta.

**Comment by michaliskambi** [comment]
We already support shaders on any X3D geometry, including on `Sphere`. 

You can use ComposedShader and ShaderPart nodes, from the standard, https://castle-engine.io/x3d_implementation_shaders.php .

Or you can use Effect, EffectPart nodes, which are CGE-specific extensions (actually, FreeWRL also implements them but we didn't test for perfect compatibielity) and allow to write shader code to enhance the "core" rendering provided the engine.

Demos of all above are available in e.g. https://github.com/castle-engine/demo-models , 

- https://github.com/castle-engine/demo-models/tree/master/shaders
- https://github.com/castle-engine/demo-models/tree/master/compositing_shaders


That said, it doesn't mean we support any GLSL code in our shader. We cannot. Each browser requires a bit different set of uniforms, due to the way its internal shaders are made (e.g. whether you do animation on GPU or not), and the OpenGL(ES) version used is also relevant (dictates what you can support). 

Opening the referenced model ( https://coderextreme.net/X3DJSONLD/src/main/personal/cgeball.x3d ) -- it uses `gl_Xxx` uniforms which have been removed in new OpenGL.

**Comment by coderextreme** [comment]
I did replace gl_Xxx with castle_Xxx, but I will attempt again.

Sigh,

John

**Comment by coderextreme** [comment]
I had to add:

uniform mat4 castle_ModelViewMatrix;
uniform mat4 castle_ProjectionMatrix;
uniform mat3 castle_NormalMatrix;
attribute vec4 castle_Vertex;
attribute vec3 castle_Normal;


to my castle.vs shader.

So it works, but there are additional warnings, unrelated to this issue.
