### ISSUE TITLE
Any help suppressing warnings?

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/view3dscene#88]
I converted gl_Xxx to castle_Xxx and added uniforms, which fixed the scene, but I believe there may be spurious warnings. However, I may not be using programmable shaders up to the state of the standards (these shaders worked in the past, I am porting them to CGE).  I am not sure similar shaders work anywhere else at this point.

Here's the X3D:

https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/personal/cgeball.x3d

Here's the shader (that works, except for warnings).

https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/shaders/castle.vs

As you can see, bias scale and power are initialized, but they are also initialized in the .x3d.  Originally, they weren't initialized in the shader.

Here's the warnings I am getting:
```
3 warnings:

GLSL: Uniform variable "bias" not found (or not used) in the shader source code
GLSL: Uniform variable "scale" not found (or not used) in the shader source code
GLSL: Uniform variable "power" not found (or not used) in the shader source code

Scene URL: "https://coderextreme.net/X3DJSONLD/src/main/personal/cgeball.x3d".
Use "File->View Warnings" menu to view these warnings again.
```

It's been a while since I dealt with shaders, so the standards may have changed, and this is my first scene with CGE based shaders, but I've been successful getting shaders like this one working in the past with X_ITE, but I'm also working on X_ITE shaders for this scene.

The scene works great, I just don't know why I am getting warnings from view3dscene.

Thanks

**Comment by coderextreme** [comment]
I did get similar warnings in FreeWRL with a similar file.  Again, the scene works ok others, except for some flicher/slow loading of shader.

**Comment by coderextreme** [comment]
I recall trying to move the fields from ComposedShader to ShaderPart, but nothing changed.  I can see that this issue might come from the fragment shader which does not use or declare the variables

**Comment by michaliskambi** [comment]
Looking at the testcase, the warnings are correct. The critical words to note is **...(or not used)...** written exactly for this reason in the warning, 

`GLSL: Uniform variable "bias" not found `**`(or not used)`**` in the shader source code`

Looking at what happens, they are indeed unused: 

- https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/shaders/castle.vs

    calculates the value of `rfac` using them, `rfac = bias + scale * pow(0.5+0.5*dot(incident, fragNormal), power);`, and then `rfac` is passed to the fragment shader...

- but https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/shaders/common.fs (used in this case, looking at https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/personal/cgeball.x3d ) doesn't use `rfac` . The line using `rfac` is commented out there, https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/shaders/common.fs#L32 .

So the GLSL compiler/linker correctly determined that `rfac` is unused, thus also `bias`, `scale` and `power` are unused. The GLSL compilers are **really** good at removing unused code. 

In effect, these uniform variables are not available to be set from the OpenGL(ES) API. That's how shader uniforms work -- from CGE point of view, we cannot tell a difference between "identifier doesn't exist in GLSL code", or "identifier exists, but is unused". See https://www.khronos.org/opengl/wiki/Uniform_(GLSL)#Active_uniforms . We decided to warn about it in CGE/view3dscene, because in case you made a typo in the uniform name in X3D (and it mismatches GLSL name) we want to warn about it.

You can:

1. Ignore the warnings. Nothing bad actually happens. 

2. Or (recommended to have clean code) remove (comment out) the lines dealing with `rfac`, `bias`, `scale` and `power`. They are indeed unused. You can use `#ifdef XXX` to easily have an option later to enable them, like 

```
...

uniform vec3 chromaticDispertion;
#ifdef USE_RFAC
uniform float bias;
uniform float scale;
uniform float power;
#endif

varying vec3 t;
...
void main()
{
   ....
    #ifdef USE_RFAC
    rfac = bias + scale * pow(0.5+0.5*dot(incident, fragNormal), power);
    #endif
}
```

This way, if you later decide you want to this code path, you can just add `#define USE_RFAC` on top of the file. Along with uncommenting relevant lines, using `rfac`, in the fragment shader.

**Comment by coderextreme** [comment]
Thanks, that’s extremely helpful.  I am forwarding to Doug, as FreeWRL has
similar warnings.

John
